version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - minha_rede

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python bookstore/bookstore/manage.py migrate && python bookstore/bookstore/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/exercicioEBAC_djangoPoetry
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - minha_rede

volumes:
  postgres_data:

networks:
  minha_rede:
    driver: bridge
