name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: bookstoreebac_db_user
          POSTGRES_PASSWORD: ShYdIoEFCpKY3rOJ6crNhQgP0ktBJ2DP
          POSTGRES_DB: bookstoreebac_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Copy database config
      run: |
        echo "DATABASE_URL=postgres://bookstoreebac_db_user:ShYdIoEFCpKY3rOJ6crNhQgP0ktBJ2DP@localhost:5432/bookstoreebac_db" > .env

    - name: Run migrations
      run: |
        poetry run python manage.py migrate

    - name: Run tests
      run: |
        poetry run python manage.py test
